### ISSUE TITLE
Alternate command palette black characters

### ISSUE THREAD

**Issue by MikNikIlin** [silvestreh/atom-material-ui#31] opened 2015-07-17 17:25 UTC
![112331](https://cloud.githubusercontent.com/assets/7029714/8753227/99477fb0-2cc2-11e5-8252-3310e26dff4c.jpg)

hard to read

**Comment by MikNikIlin** [comment] 2015-07-17 17:27
![112331](https://cloud.githubusercontent.com/assets/7029714/8753179/46d3ea98-2cc2-11e5-91fa-0e36f1e7df9f.jpg)

**Comment by silvestreh** [comment] 2015-07-17 18:27
Will look into this! Thanks!

**Comment by silvestreh** [comment] 2015-07-17 18:42
Hmm… I can't seem reproduce this. 

![captura de pantalla 2015-07-17 a las 15 41 28](https://cloud.githubusercontent.com/assets/1133339/8754503/5984bae6-2c9a-11e5-8fe3-63e8ae22b44b.png)

**Comment by silvestreh** [comment] 2015-07-18 15:25
I'm closing this issue as I fail to reproduce the bug. Feel free to reopen it if you find out how to reproduce it.

**Closed by silvestreh** 2015-07-18 15:25 UTC
Labels: bug

**Comment by MikNikIlin** [comment] 2015-07-19 12:54
UI Theme : atom-material-ui
Syntax Theme : atom-material-syntax
OS : Widonws 8.1, Ubuntu 15.04 and OS X 10.10.4
![1111](https://cloud.githubusercontent.com/assets/7029714/8765952/5c1a3fe8-2e2e-11e5-85a0-6defc345fbd1.jpg)

**Comment by silvestreh** [comment] 2015-07-19 14:54
I'm on OS X 10.10.4 and I cannot reproduce it.
