### ISSUE TITLE
Sometimes when dragging a tab it's surrounded by rectangle

### ISSUE THREAD

**Issue by roee-indegy** [silvestreh/atom-material-ui#86] opened 2015-09-02 14:47 UTC
![image](https://cloud.githubusercontent.com/assets/10956268/9634423/58cc64da-519a-11e5-8225-57c1fe372b84.png)
This happens occasionally when i drag tabs.

**Comment by silvestreh** [comment] 2015-10-01 23:20
It's been a month and I still cannot reproduce it. I'll close the issue. Feel free to reopen it if you have concise instructions on how to reproduce the bug.

**Closed by silvestreh** 2015-10-01 23:20 UTC
Labels: help wanted, unable to reproduce
